
### Test Client API 

POST http://localhost:5000/api/clients/register
Content-Type: application/json

{
  "nom": "Ahmed",
  "permis": "AB12ssdc6",
  "email": "ahmed@example.com",
  "age": 30,
  "contact": "0605623456",
  "password": "mffddfghjjjjh"
}

####
POST http://localhost:5000/api/clients/login
Content-Type: application/json

{
  "email": "sara@example.com",
  "password": "motdepasse2"
}

###
PUT http://localhost:5000/api/clients/update-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImVtYWlsIjoic2FyYUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NjU1MzE0NiwiZXhwIjoxNzQ2NTUzNDQ2fQ.F3K6PVZaBasA70Hb1gonvMBqb_12aZ32JgyuD_L60WA

{
  "nom": "hakim",
  "email": "hakim@gmail.com",
  "permis": "XYZ98",
  "age": 67,
  "contact": "060000000"
}
###
GET  http://localhost:5000/api/reservations/mes-reservations
 Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImVtYWlsIjoic2FyYUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NjYyNzY4NCwiZXhwIjoxNzQ2NjI3OTg0fQ.ovbIqkDKkEjuOz_kCWqqgHwdnz79Yx69jjeEIGxsw0I
###

PUT http://localhost:5000/api/reservations/6/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImVtYWlsIjoic2FyYUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NjYzMzkzNiwiZXhwIjoxNzQ2NjM0MjM2fQ.JVBuPDX2rh4jvtK7mAZ6ECoIdqhDdAIdLpXcwHA5vRY

{
  "annulee": true
}

#####
GET  http://localhost:5000/api/reservations-historique/mes-historiques
 Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImVtYWlsIjoic2FyYUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NjYyMTkyMSwiZXhwIjoxNzQ2NjIyMjIxfQ.KvkLB9p1oV4_d0fvFqSdKMXrSE-qWRVSKxNFanMdiwY

######
DELETE   http://localhost:5000/api/reservations-historique/delete-historique/13
 Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImVtYWlsIjoic2FyYUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NjYyMjk2MywiZXhwIjoxNzQ2NjIzMjYzfQ.OuTnK63OFvVakiulzpfB2UiZc096Q2lPiWPfSM43WHw



####  Test agence API

POST http://localhost:5000/api/agences/register
Content-Type: application/json

{
  "nom": "Agence Alpha",
  "adresse": "123 rue de Paris",
  "contact": "0601020304",
  "email": "agence@example.com",
  "password": "monmotdepasse"
}

###
POST http://localhost:5000/api/agences/login
Content-Type: application/json

{
  "email": "agence@example.com",
  "password": "monmotdepasse"
}


